# Generated by Django 5.2.7 on 2026-05-01 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stretch_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('difficulty_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BodyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_areas', to='my_app.bodyarea')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField()),
                ('date_occurred', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.bodyarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to=settings.AUTH_USER_MODEL)),
                ('pain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.paintype')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('sport', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('injury_history', models.TextField(blank=True)),
                ('saved_stretches', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StretchMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.bodyarea')),
                ('pain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.paintype')),
                ('stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.stretch')),
            ],
        ),
        migrations.CreateModel(
            name='SavedStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_app_profile', to=settings.AUTH_USER_MODEL)),
                ('stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.stretch')),
            ],
            options={
                'unique_together': {('user', 'stretch')},
            },
        ),
    ]
