# Generated by Django 5.2.7 on 2026-05-05 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labels', models.ManyToManyField(blank=True, to='my_app.routinelabel')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.routine')),
                ('stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.stretch')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='stretches',
            field=models.ManyToManyField(through='my_app.RoutineStretch', to='my_app.stretch'),
        ),
    ]
