# Generated by Django 5.2.7 on 2026-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_routinelabel_routine_routinestretch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
    ]
