# Generated by Django 5.2.7 on 2026-05-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_savedroutine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stretch',
            old_name='image_url',
            new_name='cover_image_url',
        ),
    ]
