# Generated by Django 5.2.7 on 2026-05-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_image_url_stretch_cover_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='injury_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_stretches',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
