# Generated by Django 5.2.7 on 2026-05-06 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_savedstretch_user_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_routines', to=settings.AUTH_USER_MODEL),
        ),
    ]
