# Generated by Django 5.2.7 on 2026-05-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_routine_saved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injury',
            old_name='body_area',
            new_name='location',
        ),
    ]
